version: '3.3'

services:
  db:
    image: postgres:16.1-alpine3.19
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    restart: always
    build:
      context: ./backend/
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/:/app/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
      - 443:443
    volumes:
      - static:/static/
      - media:/media/
      - certs:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  postgres_data:
  static:
  media:
  certs:
